#!/usr/bin/bash
#!/usr/bin/bash

focusedws=$(hyprctl activewindow -j | jaq -c '.workspace.id')

if [[ "$focusedws" == 'null' ]]; then
	echo 1
else
	if [[ $focusedws -eq 10 ]]; then
		echo 0
	else
		echo "$focusedws"
	fi
fi

if [ "$1" == "--once" ]; then
	exit 0
else
	socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | rg --line-buffered "workspace>>" | while read -r line; do
		case ${line%>>*} in
		"workspace")
			focusedws=${line#*>>}
			if [[ $focusedws -eq 10 ]]; then
				echo 0
			else
				echo "$focusedws"
			fi
			;;
		esac
	done
fi
